version: "3.9"

services:
  citilystbackend:
    container_name: citilyst_be_prod
    image: genqserve/citilyst-backend:latest
    build:
      context: .
      dockerfile: ./Dockerfile 
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    restart: always
    networks:
      - app_network

  redis:
    image: "redis:7.2"
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - app_network
    restart: always

networks:
  app_network:
    driver: bridge
