
services:
  citilystbackend:
    container_name: citilyst_be_debug
    image: genqserve/citilyst-backend:latest
    build:
      context: .
      dockerfile: ./Dockerfile.debug
    command: >
      sh -c "pip install debugpy && python -m debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
      - "5678:5678"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - app_network

  redis:
    image: "redis:7.2"
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - app_network
    restart: always

networks:
  app_network:
    driver: bridge
